마이페이지 초안 구현, API 업데이트에 따른 overview 수정
woowacourse-teams/2022-review-duck pull request #178
Opened 2022-08-01 15:38 UTC by DomMorello

> 많은 내용이 변경되어서 PR에 모든 사항을 글로 적는것보다는 만나서 코드리뷰를 진행하는 것이 나을 것 같다고 판단해서 PR에는 전체적으로 간단하게 작성했습니다. 함께 코드보면서 리뷰해주시면 감사하겠습니다 :)

### ReviewList 컴포넌트 
하위 container 폴더에서 ReviewList 컴포넌트에 prop으로 받는 filter 값에 따라 query 에 enabled 옵션을 줘서 선택적으로 query문을 실행하도록 구현했습니다.
```ts
function ReviewList({ filter }: Record<'filter', string>) {
  const { data: myReviews } = useGetMyReviews({ enabled: filter === TAB.MY_REVIEWS });
  const { data: myReviewForms } = useGetMyReviewForms({ enabled: filter === TAB.MY_REVIEW_FORMS });
  ...
}
```

### @Shared 디렉토리로 QuestionContent 이동
community 도메인의 MyPage 에서 사용됨에 따라 이동했습니다.

### API 레이어 생성
reviewAPI 업데이트 밑 myReviewAPI 레이어를 작성했습니다.

### 타입
기존의 타입을 최대한 유지하면서 필요한 타입을 생성했습니다. 타입 관련된 부분은 한 번에 전면 수정하기 보다는 개발을 하면서 계속해서 개선이 필요한 사항인 것 같습니다 :(

### Query key 컨벤션
사전에 의논한 대로 컨벤션 문서를 작성했고 코드레벨에서 적용했습니다

### state를 활용한 리다이렉트 path 전달
mypage 에서 회고폼이나 회고 페이지로 이동했을 때는 수정이 완료된 후에 overview 페이지로 리다이렉트 되는 것이 아닌 다시 mypage 로 와야 하기 때문에 라우팅할 때 state를 사용해서 구현했습니다. 해당 항목에 대해서 주석도 달았으니 확인 바랍니다.

### ReviewListPage -> ReviewOverviewPage 네이밍 수정

## TODO
- 며칠전 함수 만들어야 함
- Overview 페이지에서 우측 작성된 회고목록 디자인 후 구현
- 회고목록 클릭시 해당 회고로 스크롤 이동
- 회고 답변 수정 구현
->  url을 다르게 할까? 아니면 오류를 캐치해서 편집인지 생성인지를 구분할까? 의논이 필요함.
- Mypage 디자인 구현
- ReviewList 컴포넌트에서 분산된 query 및 mutation useMyReviewQueries 로 리팩토링이 필요할지? 의논이 필요함.
- SnackBar 사용할 수 있는 부분 업데이트 필요함

2022-08-01 16:54 UTC, compy-ryu requested changes
하디형님 고생하셨습니다!

시간이 늦어서 일단 크게 보이는 부분만 리뷰 남겨두었습니다!
타입 선언 부분은 아직 확인 안 했어요!

타입 부분은 데모 끝나고 한번 정리 가시죠.

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/@shared/constants/index.ts
> +};
TAB이라는 상수의 네이밍 범위가 매우 넓은 것 같습니다!
실제로는 마이페이지에서만 쓰이는 상수이니, MYPAGE_TAB으로 표현하는게 어떨까요!?

이후 다른 탭 상수가 추가된다면 서로 헷갈릴 것 같아요!

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/community/pages/MyPage/index.tsx
> +        <button onClick={() => setCurrentTab(TAB.MY_REVIEW_FORMS)}>생성한 회고 보기</button>
상단에서 이벤트 핸들러 함수 선언해서 넣어주세유!
저희 컨벤션에 맞추어 핸들러 네이밍을 통해 목적을 바로 알 수 있게하는게 좋을 것 같습니다.

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/community/pages/MyPage/index.tsx
> +        )}
```jsx
<ReviewList filter={ currentTab === TAB.MY_REVIEWS
    ? TAB.MY_REVIEWS
    : TAB.MY_REVIEW_FORMS }/>
```

스타일 차이이긴 한데, 전 보통 이렇게 하는데 어떻게 생각하십니까!

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/community/pages/MyPage/styles.module.scss
> +    width: 50vw;
⚠️ vw는 가능한 쓰시면 아니되옵니다!
가능한 퍼센트로 표현 해주세요!

화면 너비만 고려하는 것이 아닌 상위에서 새로운 컨테이너로 또 한번 래핑했을 때도 한번 생각해주십셔!

예)
만약 상위 엘리먼트의 너비가 300px 이면
50vw 옵션을 준 컨테이너는 넘쳐서 화면이 깨지게 될 가능성이 높아요.

재사용도 못하고, 해당 구조에만 종속된 스타일이 되어버립니더!

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/review/hooks/queries/useDeleteReview.ts
> +      alert(message);
Query Hook에서 alert을 띄우는건 훅의 재사용성을 떨어뜨린다고 생각헙니다!
전 alert은 UI 영역에 속해 있다 생각하고, 가능한 비즈니스 영역에서 배제시킵니다.

이 경우는 API를 위한 영역인데 UI 영역이 섞여있는건 어색한 상황인 것 같아요.
alert을 페이지 컴포넌트 상에서 처리하는건 어떨까유!

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/review/hooks/queries/useDeleteReviewForm.ts
> +      alert(message);
alert 👀

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewHeader.tsx
> +  const { data, isError, error } = useGetReviewForm(reviewFormCode);
오늘 낮에 하신 말이 이 뜻이셨군요.

말씀하신 것처럼 에러 바운더리에 맡기는 방법도 있고
커스텀훅으로 페이지 컴포넌트에서 쓰는 API들을 묶고 거기서 한번에 에러 핸들링 해주는 방법도 있을 것 같습니다.

요건 나중에 에러 처리 부분 디테일하게 생각해보고 같이 정하시죠!

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewSideMenu.tsx
> +            )}
```jsx
<Icon code="edit"/> <span>회고 수정하기</span>
```

이렇게 하는건 어떨까유.


그리고 여기서 수정하기를 검사하면
이후 페이지 네이션이 구현되면 여기 로직 못 쓸꺼 같습니다!

일단 회고 참여하기로 표현해도 될 것 같은데 형님은 어찌 생각하십니까!?

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewSideMenu.tsx
> +                  <Icon code="edit_note"></Icon>
children이 없으면 바로 닫아주세요!

<Icon code=""/>

2022-08-01 16:54 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewPage/index.tsx
> +      { reviewFormCode, answers, nickname: reviewForm.creator.nickname },
이거 저희 논의 필요할 것 같습니다!
닉네임은 이렇게 보내는 것보다는 서버 정보를 활용하는게 맞는 것 같은데 어찌 생각하시나요!

2022-08-01 19:04 UTC, compy-ryu commented on frontend/src/service/community/pages/MyPage/styles.module.scss
> +    width: 50vw;
물론 예외적인 케이스로는 100vh도 있습니다!

height: 100%를 처리하려면, 상위 엘리먼트로 계속 높이 100%를 설정해주어야 하는데
이때 100vh를 써서 상위 엘리먼트 처리 없이, 높이를 세팅할 수 있어유~~

2022-08-02 01:04 UTC, DomMorello commented on frontend/src/service/@shared/constants/index.ts
> +};
좋은 지적입니다! 수정하겠습니다 ㅎㅎ

2022-08-02 01:04 UTC, DomMorello commented on frontend/src/service/community/pages/MyPage/index.tsx
> +        <button onClick={() => setCurrentTab(TAB.MY_REVIEW_FORMS)}>생성한 회고 보기</button>
아 고친다는걸 깜빡했네요 확인했습니다!

2022-08-02 01:05 UTC, DomMorello commented on frontend/src/service/community/pages/MyPage/index.tsx
> +        )}
코드길이도 더 짧아지고 좋은 것 같습니다 ㅎㅎㅎ

2022-08-02 01:06 UTC, DomMorello commented on frontend/src/service/community/pages/MyPage/styles.module.scss
> +    width: 50vw;
오 생각못한 부분이네요 뭔가 확정된 디자인이라고 생각해서 그렇게 한 것 같은데 %로 수정하겠습니다!

2022-08-02 01:07 UTC, DomMorello commented on frontend/src/service/review/hooks/queries/useDeleteReview.ts
> +      alert(message);
음...고민했던 부분인데 해당 쿼리를 사용하는 측에서 계속 똑같은 스낵바를 열어줄 것 같아서 코드가 중복될 것 같아 여기로 넘겼는데 UI와 비즈니스 영역 관심사 분리가 안 되는 문제가 있겠네요 ㅎㅎㅎ 코드 중복이 있더라도 바깥으로 빼겠습니다!

2022-08-02 01:08 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewHeader.tsx
> +  const { data, isError, error } = useGetReviewForm(reviewFormCode);
커스텀훅에서 한 번에 에러 핸들링해주는 건 생각 못했네요! 의논해보시죠! ㅎㅎㅎㅎ

2022-08-02 01:09 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewSideMenu.tsx
> +            )}
> 이후 페이지 네이션이 구현되면 여기 로직 못 쓸꺼 같습니다!

이 부분이 이해가 잘 가지 않는데 왜 못쓰게 되는걸까요?

2022-08-02 01:16 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewSideMenu.tsx
> +                  <Icon code="edit_note"></Icon>
아 실수! 수정하겠습니다 ㅎㅎㅎ

2022-08-02 01:17 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewPage/index.tsx
> +      { reviewFormCode, answers, nickname: reviewForm.creator.nickname },
API 수정이 필요해보이네요!

2022-08-02 02:28 UTC, compy-ryu commented
하디 형님! 마이페이지 스타일링 추가 했습니다!
이어서 작업하시고, 다시 리뷰 보내주시면 확인해보겠습니다!

2022-08-02 02:29 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewOverviewPage/containers/ReviewSideMenu.tsx
> +            )}
페이지 네이션으로 회고를 10개씩 받아올 때, 21번째에 자신의 회고가 있다면
그 전까지는 수정 권한을 확인할 수 없을 것 같습니다!

2022-08-02 05:47 UTC, compy-ryu approved these changes
리뷰 반영 확인하였습니다!!!

데모데이 기간이 얼마 남지 않아 일단 approve 진행하고
다음 PR에서 이어서 디테일하게 코드 리뷰 하겠습니다!

고생하셨습니다!!!

2022-08-02 05:47 UTC, merged