어드민 페이지 구현
woowacourse-teams/2022-review-duck pull request #252
Opened 2022-08-09 08:17 UTC by woong7

2022-08-09 08:47 UTC, ulimy reviewed
안녕하세요 판다! 어드민 페이지 구현하느라 고생 많으셨습니다.
제가 리액트를 잘 몰라서 대부분의 코드리뷰가 src/main에 한정되어있는 점 양해부탁드려요.
코멘트와 함께 필드 선언 전 개행도 확인부탁드려요!😃

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/admin_react/react-admin-dashboard/README.md
> +# Getting Started with Create React App
이 부분은 판다가 작성하신건가요 혹은 기본으로 있는건가요? 필요하지 않다면 삭제해도 좋을 것 같아요!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/controller/AdminController.java
> +        log.info("uri={}, method = {}",
loginAdmin의 로깅은 common.util.Logging을, 다른 함수는 직접 구현되어있는데 common.util.Logging로 통일하면 좋을 것 같아요~

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/domain/Admin.java
> +public class Admin {
이 도메인은 비어있는데 왜 필요한가요?👀

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminQuestionAnswerResponse.java
> +    public static AdminQuestionAnswerResponse of(QuestionAnswer questionAnswer) {
매개변수가 하나인 정적팩토리메서드의 네이밍 컨벤션은 from입니다!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminReviewResponse.java
> +    AdminReviewInfoResponse reviewInfo;
private 접근제어자!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/service/AdminService.java
> +@AllArgsConstructor
특별한 이유가 없다면 접근제어자를 private으로 한정한다면 좋을 것 같아요

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/service/AdminService.java
> +    public void deleteMemberById(Long memberId) {
약속했던대로 c-r-u-d 순서대로 메서드를 정렬한다면 일관성 있는 코드가 될 것 같아요!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/review/service/ReviewService.java
> +        validateMyReview(member, review, "본인이 생성한 회고가 아니면 삭제할 x수 없습니다.");
이 x는 오타인가봐요!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/controller/AdminController.java
> +    private void validateAdmin(Member member) {
이건 argument resolver의 책임인 것 같아요. 인가니까요!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminMemberResponse.java
> +        return new AdminMemberResponse(member.getId(), member.getSocialId(), member.getSocialNickname(),
어떤 기준으로 개행을 하신건지 궁금해요!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/controller/AdminController.java
> +    @Operation(summary = "사용자를 탈퇴시킨다")
조회는 상관없지만 탈퇴나 삭제같은 경우는 테스트코드가 있어야히지않을까요?

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/member/domain/Member.java
> +    public void deleteAllInfo() {
이부분도 테스트코드 필요할 것 같아요! 추후에 사용자에게 제공될 수도 있으니까요!

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthController.java
> +import java.util.Optional;
이 친구는 어디서 쓰이길래 생긴걸까요👀

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminReviewsResponse.java
> +            .collect(Collectors.toList());
unmodifiable 컨벤션~

2022-08-09 08:47 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminReviewResponse.java
> +            .collect(Collectors.toList());
unmodifiable 컨벤션~ 여기만 그런건 아니니 전체적으로 한번 봐주세요!

2022-08-09 08:48 UTC, RunaNam requested changes
판다 어드민 페이지 구현 수고하셨습니다~!!
전체적으로 백엔드 코드에서 클래스에 한줄 띄기, toUnmodifiableList 사용하기 등의 컨벤션이 안지켜져있어요! 해당 부분도 같이 수정해주시면 좋을 것 같습니다! 👍

2022-08-09 08:48 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/admin/service/AdminService.java
> +    public void deleteMemberById(Long memberId) {
Service에서 메서드 순서는 CRUD순서가 컨벤션이라서 해당 클래스는 메서드 정렬 다시 해야될 것 같네요!

2022-08-09 08:48 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthController.java
> +import java.util.Optional;
이거 왜 이부분만 수정된거죠.....?

2022-08-09 08:48 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/admin/domain/Admin.java
> +public class Admin {
해당 클래스는 내용이 없네요...!

2022-08-09 08:53 UTC, sojukang approved these changes
어드민 페이지 고생 많으셨습니다 👍

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/App.css
> +}
ㅋㅋㅋ 로고 빙빙 도는 거도 필요한가유

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/App.js
> +      console.log(authorizationCode)
이거 왜 남기나유??

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/App.test.js
> +});
ㅋㅋㅋ 얘는 없어도 되겠네유

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/components/featuredInfo/FeaturedInfo.jsx
> +}
필요한가유??

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/components/sidebar/Sidebar.jsx
> +                            Sales
나중에 아이콘도 수정해봅시다

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/components/widgetLg/WidgetLg.jsx
> +export default function WidgetLg(){
Lg, Sm이 한번에 와닿지 않는데, 축약한 이점이 있을까요?

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/pages/member/Member.jsx
> +    console.log(param);
필요한가유??

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/pages/memberList/dummyData.js
> +
이거 이제 없어도 될 것 같은디유??

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/admin_react/react-admin-dashboard/src/pages/reviewList/ReviewList.jsx
> +          onClick={()=>axios.delete(`${props.API_URI}/reviews/${params.row.id}`, headers)}
axios.method 부분을 함수로 빼서 재활용 하는 것도 괜찮겠네유

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminMemberResponse.java
> +public class AdminMemberResponse {
한 칸 띄워주시쥬 👍

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminMemberReviewsResponse.java
> +public class AdminMemberReviewsResponse {
한 칸 띄워주시쥬 👍

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/member/domain/Member.java
>          if (o == null || getClass() != o.getClass())
Hibernate.getClass로 바꾸는 편이 좋을 것 같습니다. 그냥 getClass하면 프록시인 경우 바로 false를 리턴해서 비교가 안됩니다.

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminMembersResponse.java
> +            .collect(Collectors.toList());
UnmodifiableList가 좋을 것 같습니다👍

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminReviewFormsResponse.java
> +            .collect(Collectors.toList());
여기도 UnmodifiableList로 바꿔야겠네유!

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/admin/controller/AdminController.java
> +    public TokenResponse loginAdmin(@CookieValue(value = "refreshToken", required = false) Cookie cookie,
안 쓰는 메서드로 보입니다!

2022-08-09 08:53 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/admin/controller/AdminController.java
> +    private void validateAdmin(Member member) {
여기서 Admin 검증이 이뤄지는군요

2022-08-09 08:55 UTC, woong7 commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminQuestionAnswerResponse.java
> +    public static AdminQuestionAnswerResponse of(QuestionAnswer questionAnswer) {
좋습니다 👍

2022-08-09 08:55 UTC, woong7 commented on backend/reviewduck/src/main/java/com/reviewduck/admin/domain/Admin.java
> +public class Admin {
멤버와 어드민을 분리하려 했던 과거의 흔적인데 놓쳐버렸네요!

2022-08-09 08:55 UTC, woong7 commented on backend/reviewduck/src/main/java/com/reviewduck/admin/controller/AdminController.java
> +        log.info("uri={}, method = {}",
통일할게요!

2022-08-09 08:56 UTC, woong7 commented on backend/reviewduck/src/main/java/com/reviewduck/admin/dto/response/AdminReviewResponse.java
> +    AdminReviewInfoResponse reviewInfo;
👍

2022-08-09 08:56 UTC, woong7 commented on backend/reviewduck/src/main/java/com/reviewduck/admin/service/AdminService.java
> +@AllArgsConstructor
좋습니다!

2022-08-09 08:58 UTC, woong7 commented on backend/reviewduck/src/main/java/com/reviewduck/review/service/ReviewService.java
> +        validateMyReview(member, review, "본인이 생성한 회고가 아니면 삭제할 x수 없습니다.");
수정했습니다!

2022-08-10 01:14 UTC, RunaNam approved these changes

2022-08-10 01:16 UTC, ulimy approved these changes
피드백 꼼꼼하게 반영해주신 부분들 잘봤습니다! 
ReviewForm에 isActive final만 삭제 부탁드려요^~^

2022-08-10 01:20 UTC, merged