TemplateStore 페이지 초안 작성
woowacourse-teams/2022-review-duck pull request #264
Opened 2022-08-09 15:13 UTC by DomMorello

아직 API 협의가 이루어지지 않은 상황에서 기존 컨벤션에 맞도록 초안을 작성했습니다.

- MSW 모킹
- hook 작성
- TODO: 라우팅으로 필터링탭(트랜딩, 최신) 구현 예정(이 부분은 API 회의 이후에 적용하겠습니다.)

2022-08-09 15:23 UTC, compy-ryu commented on frontend/src/mocks/handlers/template.js
> +];
더미 데이터를 mocks/data.js로 
따로 분리해서 더미 데이터만 다 같이 관리하는건 어떻게 생각하시나요!?

2022-08-09 15:30 UTC, compy-ryu commented on frontend/src/service/@shared/constants/index.ts
> +  TEMPLATE_STORE: '/template-store',
오! 이제 페이지가 좀 생기다보니 어느정도 틀이 잡히는 것 같은데
혹시 저희 페이지 URI도 아래와 같이 한번 정리하면 좋을 것 같은데 어떻게 생각하십니까!?
(이 방식이 괜찮으시다면, 리뷰 영역은 제가 리팩토링 하면서 바꾸겠습니다!)

## 템플릿
- /template/list
- /template/view/:id
- /template/editor


## Review 영역
- review/form/:id (reviewForm)
- review/answer/:id (rewview)
- review/join
- review/:reviewFormCode (overview)

2022-08-09 15:34 UTC, compy-ryu commented on frontend/src/PageRoutes.tsx
>        </Route>
요 친구들 맨 위로 올리고, 같은 뎁스에서 index MainPage가 가장 앞으로 오게 하는건 어떻게 생각하십니까!?
지금 생각해보니, 페이지 접속 플로우대로 위치시키는게 저희가 나중에 코드 읽을 때도 더 좋을 것 같기도 헙니다!!

2022-08-09 15:36 UTC, compy-ryu reviewed
형님 리뷰라기보다는 애매한(?) 코멘트 몇개 달아보았습니다.
한번 확인 부탁드릴께요!!

2022-08-09 15:41 UTC, compy-ryu commented on frontend/src/service/@shared/hooks/queries/template/useGet.ts
> +function useGetTemplates(queryOptions?: UseQueryOptions<GetTemplatesResponse[], ErrorResponse>) {
GetTemplatesResponse의 타입이 배열으로 한정되어있다면
타입 선언부에서부터 배열으로 명시해주는건 어떨까유!?

2022-08-09 15:47 UTC, compy-ryu requested changes

2022-08-09 15:47 UTC, compy-ryu commented on frontend/src/service/template/pages/TemplateStorePage/index.tsx
> +        ))}
스타일 차이입니다만!!

여기서 map 돌릴 때 템플릿 리스트란 네이밍이 이미 map 앞에 명시 되어있고
key 이름으로도 충분히 무엇인지 알 수 있는 것 같아보이는데

혹시 아래와 같이 구조분해 해서 출력하는건 어떨까요!?

```jsx
templates.map(({ templateId, templateTitle, /* 생략 */ }) => (
  <div key={templateId}>
    <Text>{templateTitle}</Text>
    <Text>{templateDescription}</Text>
    <Text>{getElapsedTimeText(updatedAt)}</Text>
    <Text>{`${usedCount}회 사용됨`}</Text>
    <div
      style={{
        backgroundImage: `url(${creator.profileUrl})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        height: '30px',
        width: '30px',
      }}
    ></div>
    <Text>{`by ${creator.nickname}`}</Text>
  </div>
))}

```

2022-08-10 01:01 UTC, DomMorello commented on frontend/src/mocks/handlers/template.js
> +];
좋습니다!

2022-08-10 01:03 UTC, DomMorello commented on frontend/src/service/@shared/constants/index.ts
> +  TEMPLATE_STORE: '/template-store',
좋은 생각입니다 훨씬 직관적이네요 ㅎㅎ

2022-08-10 01:03 UTC, DomMorello commented on frontend/src/PageRoutes.tsx
>        </Route>
넵 좋습니다 ㅎㅎㅎ

2022-08-10 01:04 UTC, DomMorello commented on frontend/src/service/@shared/hooks/queries/template/useGet.ts
> +function useGetTemplates(queryOptions?: UseQueryOptions<GetTemplatesResponse[], ErrorResponse>) {
음 좋습니다!

2022-08-10 01:04 UTC, DomMorello commented on frontend/src/service/template/pages/TemplateStorePage/index.tsx
> +        ))}
오호 좋은 스타일인것같아요 앞으로 애용하겠습니다!

2022-08-10 01:17 UTC, DomMorello commented on frontend/src/service/@shared/constants/index.ts
> +  TEMPLATE_STORE: '/template-store',
`editor` 말고 `edit` 으로 하겠습니다 ㅎㅎ!

2022-08-10 02:07 UTC, compy-ryu approved these changes
고생하셨습니다!!!!

2022-08-10 02:07 UTC, merged