회고 폼 생성/수정 페이지 리팩토링
woowacourse-teams/2022-review-duck pull request #271
Opened 2022-08-10 16:17 UTC by compy-ryu

## 리팩토링 포인트
- 지저분 하였던 API 통신 처리를 페이지에서 최대한 은닉하고
관련 상태들을 커스텀훅에서 명시적으로 반환하도록 구조 개선을 시도하였습니다.

- 리다이렉트 URL을 useLocation의 state로 넘겨주는 것이 아닌, query string으로 처리하도록 구조를 변경하였습니다.

- 전반적으로 네이밍도 함께 수정해보았습니다.

2022-08-10 16:27 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewFormEditorPage/index.tsx
>    );
이 부분을 어떻게 처리할 지 살짝 고민했었습니다 🤔

단순한 상태들(useState - reviewTitle, useQuestions)도
전부 useReviewFormEditor 커스텀훅으로 은닉한 뒤, 페이지 컴포넌트에서 다시 꺼내올까 했었습니다만

핸들러에서 쓰기 위해선 다시 꺼내와야하고, 굳이 useQuestions 커스텀훅을 useReviewFormEditor 커스텀훅으로
또 다시 래핑했을 때 얻는 이점을 못 느끼겠어서

일단 이런 상태들은 전과 같이 페이지 컴포넌트 그대로 꺼내두었습니다.

결론적으로 현재의 useReviewFormEditor 커스텀훅은 API 관련 상태들과 로직들을
조금 더 명시적이게 바꿔 주는 용도로만 쓰고있습니다.

2022-08-11 01:10 UTC, ulimy commented
공룡아저씨화이팅!🦖

2022-08-11 02:39 UTC, DomMorello requested changes
코멘트 한 번 확인하시고 생각 말해주세요! ㅎㅎㅎ

2022-08-11 02:39 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewFormEditorPage/index.tsx
>    );
useQuestions 에서 관리되는 상태는 페이지 전체에서 사용되는 제어 컴포넌트의 고유 상태이기 떄문에 페이지에 있는 것이 더 명시적이라고 생각합니다.

2022-08-11 02:39 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewFormEditorPage/index.tsx
> +function ReviewFormEditorPage() {
기존의 페이지 이름보다 좀 더 명시적이라서 좋네요!

2022-08-11 02:39 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewFormEditorPage/index.tsx
>        navigate(PAGE_LIST.HOME);
loadError 가 있는 경우 HOME으로 가는 것이 아니라 redirectUri로 redirect 시키는 것은 어떨까요?

마이페이지에서도 접근 가능하고, 이후 템플릿에서도 접근이 가능할 것 같은데 에러가 발생했다고 HOME으로 무작정 가는 것이 조금 어색합니다ㅠ

2022-08-11 02:39 UTC, DomMorello commented on frontend/src/service/review/pages/ReviewFormEditorPage/index.tsx
> +    submitReviewForm(
이 부분이 개인적으로 처음 보는 사람이 보면 어색할 수 있을 것 같습니다.

submitReviewForm 으로 네이밍을 명시적으로 하되 `submitReviewForm.mutate()` 라고 muation이라는 것을 보여주는 것은 어떤가요?

2022-08-11 05:14 UTC, compy-ryu commented
피드백 반영 완료! 확인 부탁드립니다!

2022-08-11 06:29 UTC, DomMorello approved these changes
확인했습니다! ㅎㅎ

2022-08-11 06:29 UTC, compy-ryu commented on frontend/src/service/review/pages/ReviewFormEditorPage/index.tsx
>        navigate(PAGE_LIST.HOME);
맞습니다! 반영 완료하였습니다! [389a1ec](https://github.com/woowacourse-teams/2022-review-duck/pull/271/commits/389a1ec2fb10eeab349b59f5c31e3c880ed9cc9a)

2022-08-11 06:29 UTC, merged