회고, 멤버 관련 기능 추가
woowacourse-teams/2022-review-duck pull request #298
Opened 2022-08-15 08:07 UTC by RunaNam

- 회고 답변에 title 추가
- 로그인시 깃헙 프로필 사진, 닉네임 동기화
- overview 페이지 로그인 없이 볼 수 있도록 수정

2022-08-15 08:45 UTC, sojukang requested changes
고생하셨습니다 👍. 리뷰 몇 개 남겼습니다.

2022-08-15 08:45 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +    private static final Member MEMBER_NOT_LOGIN = new Member("-1", "socialNickname", "nickname", "url");
`-1`이 Resolver가 알아야 할 정보는 아닌 것 같아요. 생성자를 추가하거나 적절한 네이밍의 Static factory method로 캡슐화 하는 건 어떨까요?

2022-08-15 08:45 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +        if (isLoginRequired(request)) {
로그인이 필요한 경우 로그인 하지 않은 멤버를 반환하는 게 이상한 것 같습니다.

2022-08-15 08:45 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +    private boolean isLoginRequired(HttpServletRequest request) {
토큰이 필요한 상황에 토큰이 없는 경우 isLoginRequired가 true가 되어 MEMBER_NOT_LOGIN이 반환 되는데, 토큰 만료가 지났거나 유효하지 않은 토큰이라도 접근 되어야 하지 않을까요?

2022-08-15 08:45 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +    private boolean isTokenRequired(HttpServletRequest request) {
토큰이 필요한 경우가 `"/api/review-forms/\\w{8}/reviews"`해당 URL에만 한정되는 건 아니라 네이밍이 맞지 않는 것 같아요.

2022-08-15 08:45 UTC, sojukang commented on backend/reviewduck/src/test/java/com/reviewduck/review/acceptance/ReviewFormAcceptanceTest.java
> +    private static final String invalidToken = "tokentokentoken.invalidinvalidinvalid.tokentokentoken";
ㅋㅋㅋ

2022-08-15 08:45 UTC, sojukang commented on backend/reviewduck/src/test/java/com/reviewduck/review/acceptance/ReviewFormAcceptanceTest.java
> +        @DisplayName("로그인하지 않은 상태로 조회할 수 있다.")
ㅋㅋㅋ

2022-08-15 08:56 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +    private static final Member MEMBER_NOT_LOGIN = new Member("-1", "socialNickname", "nickname", "url");
그렇겠네요...! `Member` 내에서 생성할 수 있도록 수정해보겠습니다.

2022-08-15 08:57 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +        if (isLoginRequired(request)) {
해당 부분은 제가 메서드 명을 잘못 지정한 것 같습니다 😢 아래 코멘트와 함께 수정하겠습니다.

2022-08-17 05:48 UTC, sojukang approved these changes
아휴~ 고생하셨습니다👍

2022-08-17 05:48 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/member/controller/MemberController.java
> +    @GetMapping("/{socialId}")
자신의 정보만 조회할 수 있었는데 이제 다른 사용자의 정보도 조회할 수 있군요! 
그런데 컨트롤러는 멤버의 식별자인지만 알면 될 것 같은데 `socialId`라는 구체적인 정보까지는 몰라도 되지 않을까요?

2022-08-17 05:48 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/review/controller/ReviewController.java
> +    @GetMapping(params = "member")
URL 기준의 Path가 아니라 Query Param으로 정의하신 이유가 있나요?

2022-08-17 05:48 UTC, sojukang commented on backend/reviewduck/src/test/java/com/reviewduck/member/acceptance/MemberAcceptanceTest.java
> +            MemberResponse memberResponse = get("/api/members/1", accessToken)
memberId를 변수로 분리하는 건 어떨까요?

2022-08-17 05:48 UTC, sojukang commented on backend/reviewduck/src/test/java/com/reviewduck/review/service/ReviewFormServiceTest.java
> +            ReviewForm savedReviewForm = saveReviewForm(member1, "title1");
"title1"을 계속 중복 사용하는데 변수로 선언하는 건 어떨까요?

2022-08-17 06:49 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/member/controller/MemberController.java
> +    @GetMapping("/{socialId}")
`id`로 수정하겠습니다!

2022-08-17 06:50 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/review/controller/ReviewController.java
> +    @GetMapping(params = "member")
해당 부분은 `review` 리소스의 정보값이라기보다는 `member`의 id로 필터링된 값이라고 생각하여 QueryParam으로 정의하였습니다.

2022-08-17 06:50 UTC, RunaNam commented on backend/reviewduck/src/test/java/com/reviewduck/member/acceptance/MemberAcceptanceTest.java
> +            MemberResponse memberResponse = get("/api/members/1", accessToken)
분리하겠습니다!

2022-08-17 07:22 UTC, woong7 approved these changes
반영 잘 해주셨네요~

2022-08-17 09:48 UTC, sojukang approved these changes
회고, 멤버 관련 기능 추가 고생하셨습니다👍.

2022-08-17 09:48 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/auth/config/AuthenticationPrincipalConfig.java
> +            .addPathPatterns("/api/**")
*에서 **로 바꾼 이유는 무엇인가요?

2022-08-17 09:48 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthInterceptor.java
> +            request.getRequestURI().matches("/api/reviews") && request.getParameterMap().containsKey("member");
member가 key로 request에 존재하기만 해도 될까요?

2022-08-17 09:48 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/common/controller/ControllerAdvice.java
> +        e.printStackTrace();
printStackTrace를 추가한 이유가 있나요?

2022-08-17 09:48 UTC, sojukang commented on backend/reviewduck/src/test/java/com/reviewduck/review/service/ReviewServiceTest.java
> +        void findByReviewFormCode() throws InterruptedException {
관련 모든 테스트에 `throws InterruptedException`이 붙었는데, 다른 방법은 없었을까요?

2022-08-17 09:50 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/auth/config/AuthenticationPrincipalConfig.java
> +            .addPathPatterns("/api/**")
* 는 하위경로를 한 뎁스만 확인하나, **는 모든 하위경로를 확인하기 때문입니다.

2022-08-17 09:51 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthInterceptor.java
> +            request.getRequestURI().matches("/api/reviews") && request.getParameterMap().containsKey("member");
네! 해당 값에 대한 처리는 이후 controller 단의 책임이라고 보았습니다.

2022-08-17 09:51 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/common/controller/ControllerAdvice.java
> +        e.printStackTrace();
실수입니다... 지우도록 하겠습니다!!!

2022-08-17 09:52 UTC, RunaNam commented on backend/reviewduck/src/test/java/com/reviewduck/review/service/ReviewServiceTest.java
> +        void findByReviewFormCode() throws InterruptedException {
테스트중 updatedAt 정렬 문제로 인해 `Thread.sleep` 메서드를 호출하다보니 해당 부분을 불가피하게 추가하게 되었습니다. 더 찾아보고 혹시 다른 방법이 있으면 추후 수정하도록 하겠습니다.

2022-08-17 10:13 UTC, ulimy approved these changes
확인했습니다!

2022-08-17 10:13 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/common/controller/ControllerAdvice.java
> +        e.printStackTrace();
이 부분은 삭제 부탁드려요!

2022-08-17 10:13 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +        List<String> regexes = List.of(
interceptor의 isAuthenticationNotRequired에서 uri와 메서드를 확인하고있는데 이 함수가 추가적으로 존재하는 이유가 궁금합니다!

2022-08-17 10:13 UTC, ulimy commented on backend/reviewduck/src/test/java/com/reviewduck/member/acceptance/MemberAcceptanceTest.java
> +    class updteNickname {
해당 사용자가 아닌 경우 닉네임 수정이 안되는 테스트코드도 추가되면 좋을 것 같아요

2022-08-17 10:13 UTC, ulimy commented on backend/reviewduck/src/test/java/com/reviewduck/member/acceptance/MemberAcceptanceTest.java
> +    class updteNickname {
그리고 updte -> update 오타네요!

2022-08-17 10:13 UTC, ulimy commented on backend/reviewduck/src/test/java/com/reviewduck/review/acceptance/ReviewAcceptanceTest.java
> +    @DisplayName("개인이 작성한 회고 조회")
특정 멤버, 개인 중 하나로 통일하면 좋을 것 같아요

2022-08-17 10:22 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +        List<String> regexes = List.of(
uri 및 메서드 검증하여 들여보내는 것은 interceptor가 하고 argumentResolver에서는 토큰이 있다면 해당 member를, 없다면 가짜 member를 돌려주는 일만 한다고 설명 들었던 것 같아서요!

2022-08-17 10:23 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthenticationPrincipalArgumentResolver.java
> +        List<String> regexes = List.of(
만약 특별한 이유 없이 추가적으로 존재하는거라면 불필요하게 관리 포인트가 늘어난 건 아닌지 고민해보면 좋을 것 같아요

2022-08-17 10:27 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/auth/controller/AuthInterceptor.java
> +            request.getRequestURI().matches("/api/review-forms") && request.getParameterMap().containsKey("member");
해당 부분의 경우 현재 확인하는 uri가 많아진 상황이라서 enum으로 리팩토링하는 것이 더 좋을 것 같네요.

2022-08-17 10:27 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/common/controller/ControllerAdvice.java
> +        e.printStackTrace();
삭제했습니다!

2022-08-17 10:28 UTC, ulimy approved these changes
확인했습니다!
빠른 협업을 위해 기능이 정상작동한다면 일단 머지하고 추후에 리팩토링 및 테스트 코드를 추가합시다!

2022-08-17 10:28 UTC, ulimy commented on backend/reviewduck/src/main/java/com/reviewduck/review/dto/response/ReviewsResponse.java
> +    public static ReviewsResponse of(List<Review> reviews, String socialId, Member member) {
from -> of 변경까지 꼼꼼하고 좋네요!

2022-08-17 10:28 UTC, sojukang approved these changes
고생하셨습니다.

2022-08-17 10:28 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/member/controller/MemberController.java
> +    @GetMapping("/{socialId}")
다시 socialId로 수정한 이유는 무엇인가요?

2022-08-17 10:28 UTC, sojukang commented on backend/reviewduck/src/main/java/com/reviewduck/member/dto/response/MemberResponse.java
> +            member.equals(loginMember),
프레젠테이션 계층에서 equals 메서드로 엔티티 동일성 비교를 할 때 문제는 없을까요?

2022-08-17 10:29 UTC, merged

2022-08-17 12:46 UTC, RunaNam commented on backend/reviewduck/src/test/java/com/reviewduck/review/acceptance/ReviewAcceptanceTest.java
> +    @DisplayName("개인이 작성한 회고 조회")
`사용자`가 로 수정하겠습니다.

2022-08-17 12:48 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/member/dto/response/MemberResponse.java
> +            member.equals(loginMember),
현재는 OSIV를 사용하고있기 때문에 프록시 문제에 자유로운 상태이지만, 추후에는 문제가 생길 수 있는 부분같습니다. 레벨 4때 마저 수정하면 될 것 같아요.

2022-08-17 12:52 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/member/controller/MemberController.java
> +    @GetMapping("/{socialId}")
`id`라는 값의 경우에는 member의 pk인 id값이 명확히 존재하고 있으며, `socialId` 라는 값을 조금 더 명확히 하기 위해서 (혼동을 막기 위해) `socialId`라는 값으로 명시하였습니다.

2022-08-17 12:52 UTC, RunaNam commented on backend/reviewduck/src/main/java/com/reviewduck/member/controller/MemberController.java
> +    @GetMapping("/{socialId}")
id라는 값의 경우에는 member의 pk인 id값이 명확히 존재하고 있으며, socialId 라는 값을 조금 더 명확히 하기 위해서 (혼동을 막기 위해) socialId라는 값으로 명시하였습니다