전반적인 리팩토링 진행
woowacourse-teams/2022-review-duck pull request #371
Opened 2022-09-08 10:39 UTC by DomMorello

### 구현 항목

- [ ] SmallProfileCard 컴포넌트 > Profile 컴포넌트로 전환
- [x] flex-container column 제거 후 FlexContainer로 변경
- [x] grid-template: row 45% 45%; 제거
- [x] 템플릿 API URL 상수 처리
- [x] FieldSet 컴포넌트 합성 컴포넌트 전환
- [x] line-height %로 변경
- [x] 컴포넌트에서 propTypes 일괄 제거
- [x] 닉네임 변경 쿼리 무효화 처리
- [x] 닉네임 변경 시 유효성 검사 영역 분리
- [x] export interface ComponentNameProps 컨벤션 통일

### SmallProfileCard 컴포넌트
이 컴포넌트를 Profile 컴포넌트로 대체하자고 제안하셨는데 거꾸로 그냥 살려두자는 제안을 해봅니다 ㅎㅎㅎㅎ

문제1. Profile 내부적으로 링크를 갖고 있어서 템플릿카드에서 클릭시에 템플릿으로 이동한 후에 뒤로가기를 하면 프로필페이지로 가게 됩니다. 링크로 이동했다가 또 이동하는 문제가 있었습니다.

문제2. 디자인 수정이 좀 필요했습니다. 기존의 SmallProfileCard 디자인을 그대로 가져가서 적용해서 확장하려고 하다보니 결국엔 그냥 다른 컴포넌트가 따로 있는 것과 크게 다를 것 없다는 생각이 들었습니다.

이 문제들을 확장성 있게 노력해서 Profile 컴포넌트를 확장할 수 있겠지만 이렇게까지 해서 재사용성을 늘려야 할까라는 생각이 들어서 잠깐 멈췄습니다. 

> 피드백 주시면 감사하겠습니다 :)

2022-09-08 14:22 UTC, compy-ryu requested changes
형님 고생하셨습니다!!! 리뷰 간단한(?) 것 조금 남겨보았습니다.
한번 확인 부탁드릴께요!

---
흠 애매하긴 하네요...

그럼 혹시 Profile에서 링크를 제거하고
Profile 컴포넌트의 자식 컴포넌트들에 className으로 스타일만 추가로 입히는 식으로 적용해보는쪽은 어떨까요!?

아니면 SmallProfileCard 컴포넌트는 유지하되, 내부적으로는 Profile 컴포넌트를 쓰고 SmallProfileCard에서 한번에 스타일 다시 입혀주는식으로는 어떤가요!?

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/common/components/Button/index.tsx
> +interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
형님 그... 컴포넌트 타입들 기본적으로 export 해주기로 했었....는데 디테일하게 적어두지 않아서 혼동 있었던 것 같습니다.
이건 저희 나중에 같이 고칩시다!!

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/common/components/ErrorBoundary/index.tsx
> +import { Component, ReactNode } from 'react';
그리고 위와 같이 변경된 후 React import도 제거 부탁드립니다!

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/common/components/FieldSet/index.tsx
> +import Text from 'common/components/Text';
index에서 모아서 export 처리해주었는데, import가 두번 되어있네요! 고쳐주시면 감사하겠습니다!

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/common/components/FieldSet/index.tsx
> +interface ContainerProps {
컴포넌트 타입은 export 기본적으로 달아줄 예정이니
FieldSetContainerProps, FieldSetTitleProps와 같이 네이밍 하는건 어떨까유!?

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/common/components/FlexContainer/index.tsx
> +  gap?: 'small' | 'medium' | 'small-large' | 'large' | 'small-xlarge' | 'xlarge';
gap을 새로 추가하셨는데 혹시 기존의 small, medium, large로 바꾸었을때는 어색했었나요!?
FlexContainer에서 gap의 허용 범위가 너무 넓어지면, 각 위치들의 간격에서 통일성 없어질까해서요!!

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/service/@shared/pages/modals/ModalReviewJoin/index.tsx
> +        <FieldSet.Description description="회고 참여를 위한 코드를 입력해주세요." />
여기도 위 리뷰와 같습니다!

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/service/@shared/validator/user.ts
> +}
저희 유효성 검사 로직을 전부 정규식으로 전환하는거 어떻게 생각하시나요..!? 해놓으면 엄청 깔끔할 것 같은 느낌 아닌 느낌이..

2022-09-08 14:22 UTC, compy-ryu commented on frontend/src/service/review/components/QuestionEditor/index.tsx
>  import TextBox from 'common/components/TextBox';
여기도 이상하게 common/components에서 한번에 import 해올 수 있었는데 다 나뉘어져있지만...!

이거 프로젝트 초반에 쓰던 컴포넌트입니다.
안 쓰는 컴포넌트라 제가 지웠어요!!

2022-09-12 09:30 UTC, DomMorello commented on frontend/src/common/components/Button/index.tsx
> +interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
외부에서 사용하지 않는데도 export를 하자는건가요?

2022-09-12 09:30 UTC, DomMorello commented on frontend/src/common/components/ErrorBoundary/index.tsx
> +import { Component, ReactNode } from 'react';
아 확인했씁니다!

2022-09-12 09:31 UTC, DomMorello commented on frontend/src/common/components/FieldSet/index.tsx
> +import Text from 'common/components/Text';
확인했습니다!

2022-09-12 09:31 UTC, DomMorello commented on frontend/src/common/components/FieldSet/index.tsx
> +    <FlexContainer className={cn(styles.description)} align="center" direction="row">
확인이요!

2022-09-12 09:32 UTC, DomMorello commented on frontend/src/common/components/FlexContainer/index.tsx
> +  gap?: 'small' | 'medium' | 'small-large' | 'large' | 'small-xlarge' | 'xlarge';
기존의 디자인을 최대한 따라가보려고 했었습니다 음 ... 디자인 적으로 많이 어색하지 않으면 기존에 있었던 세 가지 사이즈 중 하나로 해보겠습니다 ㅎㅎ

2022-09-12 09:32 UTC, DomMorello commented on frontend/src/service/@shared/components/QuestionCard/index.tsx
>        </Text>
확인했습니다!

2022-09-12 09:33 UTC, DomMorello commented on frontend/src/service/@shared/pages/modals/ModalReviewJoin/index.tsx
> +        <FieldSet.Title title="참여 코드" />
오 알겠습니다!

2022-09-12 09:33 UTC, DomMorello commented on frontend/src/service/@shared/pages/modals/ModalReviewJoin/index.tsx
> +        <FieldSet.Description description="회고 참여를 위한 코드를 입력해주세요." />
좋습니다

2022-09-12 09:33 UTC, DomMorello commented on frontend/src/service/@shared/validator/user.ts
> +}
좋습니다 정규식으로 해볼게요 ㅎㅎ

2022-09-12 09:34 UTC, DomMorello commented on frontend/src/service/review/components/QuestionEditor/index.tsx
>  import TextBox from 'common/components/TextBox';
어 그럼 일단 신경안쓰겠습니다 ㅎㅎ

2022-09-12 09:56 UTC, DomMorello commented on frontend/src/common/components/ErrorBoundary/index.tsx
> +import { Component, ReactNode } from 'react';
React.어떤타입 이런 부분에서는 문제가 없는데 이상하게 createElement 앞에 있는 React 에서는 
```
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)
```
해당 에러가 발생해서 import를 해줘야 할 것 같습니다 ㅎㅎ

2022-09-12 11:46 UTC, compy-ryu commented on frontend/src/common/components/Button/index.tsx
> +interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
옙 맞습니다!

외부 컴포넌트에서 범용 컴포넌트를 기반으로 새로운 컴포넌트를 만들 때 범용 컴포넌트의 타입들도
꺼내 써야되는 경우가 가끔 생기더라구요.

그때 그때 수정하는 것보다는 범용 컴포넌트는 export를 미리해두는게 어떨까해서 제안드렸었어요.
export를 미리 해두어도 마이너스보다는 플러스가 많을 것 같아보여서요!

2022-09-12 11:47 UTC, compy-ryu commented on frontend/src/common/components/ErrorBoundary/index.tsx
> +import { Component, ReactNode } from 'react';
아 createElement를 쓰고 있었군요. 그럼 그대로 유지합시다!!

2022-09-12 11:48 UTC, compy-ryu commented on frontend/src/common/components/FlexContainer/index.tsx
> +  gap?: 'small' | 'medium' | 'small-large' | 'large' | 'small-xlarge' | 'xlarge';
최고입니다 형님

2022-09-12 11:48 UTC, compy-ryu commented on frontend/src/service/@shared/validator/user.ts
> +}
헉 부탁드리는거 아니라 같이 하자는 말이였어요

2022-09-12 11:51 UTC, compy-ryu approved these changes
형님 쉬는 날인데도 불구하고 리뷰 반영해주셔서 감사합니다.. 👍

고생하셨습니다!! 머지할께요!

2022-09-12 11:51 UTC, merged