프로필 페이지 리팩토링 및 생성한 템플릿 조회 기능 추가
woowacourse-teams/2022-review-duck pull request #403
Opened 2022-09-19 07:02 UTC by DomMorello

- 전반적으로 합성 컴포넌트 방식을 사용하여 명시적으로 컴포넌트를 분리했습니다.

2022-09-19 07:06 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +      }
어떻게든 하나로 해결해보고 싶었는데 타입문제를 해결하지 못했습니다ㅠㅠ..

매개변수로 받는 index 가 never 가 돼버려서 뮤테이션의 경우는 타입 assertion이 불가능한 구조라 API 레이어 측에서 타입을 크게 넓혀주는 것보다는 사용하는 이 핸들러 안에서만 이런 식으로 분기하는게 더 낫겠다고 판단했습니다.

2022-09-19 07:45 UTC, compy-ryu requested changes
형님 코멘트 살짝 남겨보았습니다!
확인 부탁드립니다.

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +  if (!queries) return <></>;
여기 타임라인 페이지 주석처럼 에러 바운더리와 서스펜스를 사용하고 있다고 주석이 필요할 것 같아요!
다른 사람이 보았을 땐, 미완성된 기능으로 오해할 수 있을 것 같습니다!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +  const queries = useProfilePageQueries(currentTab as Tabs, socialId, pageNumber);
지금과 같이 currentTab을 가져오고 있을 때 currentTab이 Tabs인지 확정할 수 있을까요!?
`/?tab=compy`를 넣는다면 Tabs 타입은 `compy`가 되어버립니더!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +        deleteTemplateMutation.mutate(index as number, {
어떤건 as number / string 저희 컨벤션이 통일 안되어있는 것 같습니다!

혹시 페이지 넘버링은 이제 number 타입으로 통일하는것 괜찮으신가유!
그럼 mutation 타입 문제도 해결할 수 있을 것 같아요!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +            onClick={handleEditProfile}
`onClick` prop 네이밍을 클릭 했을 때 어떤 것을 클릭하는지 명시해주는것은 어떨까요!?
핸들러를 통해 어떤 행동을 하는지 알 수는 있지만, 해당 컴포넌트의 어떤 UI 요소와 인터렉션이 이뤄지는지 바로 알 수 있으면 좋겠어유!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +          <Controller.TabNavigator currentTab={currentTab as Tabs} onClick={handleChangeTab} />
여기도요!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +        <ItemList>
ItemList보다 ArticleList는 어떨까유!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +          ))}
Questions는 페이지 컴포넌트로 다시 감싸는것보다는 여기서 그대로 사용하는건 어떨까요!?
반복되는 Item 네이밍으로 어떤 컨텐츠가 들어가는지 모르겠숩니다!

2022-09-19 07:45 UTC, compy-ryu commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +      description: '이제 누구도 해당 회고를 볼 수 없습니다.',
그 볼 수 없는건 맞긴헌데... ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-09-20 01:09 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +  if (!queries) return <></>;
알겠습니다!

2022-09-20 01:17 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +  const queries = useProfilePageQueries(currentTab as Tabs, socialId, pageNumber);
근데 지금 compy를 넣어도 잘 작동하네요 작동하지 않도록 하고 타입은 저렇게 확정짓는게 좋다고 생각합니다. 그냥 string이면 타입이 너무 넓게 잡혀있는거 아닐까요? 

searchParam은 런타임에 정해지기 때문에 TS 에서 잡아낼 수 없습니다. 그래서 개발 단계에서 컴파일 타임에 타입체크를 해줌으로써 오류를 방지하는 것이 TS 를 잘 활용하는 방법 같습니다. 다만 위에 말했듯이 param이 이상한 값일 떄는 런타임에 정해지는 것이기 때문에 그 때 따로 처리가 필요할 것 같습니다.

2022-09-20 01:25 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +        deleteTemplateMutation.mutate(index as number, {
index는 pageNumber가 아니라 reviewId, reviewFormCode, templateId 입니다!

2022-09-20 01:30 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +            onClick={handleEditProfile}
범용컴포넌트가 아닌 큰 단위의 복합적인 컴포넌트에서는 다양한 버튼이 있을 수 있으므로 props 의 이름을 적절하게 명시해주는것이 더 좋은 방법이겠네요! 'onEditClick' 으로 수정하겠습니다!

2022-09-20 03:56 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +        <ItemList>
좋습니다!

2022-09-20 03:57 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +          ))}
좋습니다!

2022-09-20 03:57 UTC, DomMorello commented on frontend/src/service/user/pages/ProfilePage/index.tsx
> +      description: '이제 누구도 해당 회고를 볼 수 없습니다.',
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ다른 말을 생각해볼게요

2022-09-21 03:33 UTC, merged