회고 폼 생성 / 회고 답변 페이지 완성 & 1차 스프린트 종료 후 리팩터링
woowacourse-teams/2022-review-duck pull request #63
Opened 2022-07-12 06:11 UTC by compy-ryu

- 회고 폼 생성 페이지 추가
- 회고 답변 페이지 추가
- 1차 스프린트 종료 후 목표 기능들 리팩터링 작업
- import 자동 정렬 처리 & prettier 자동 정렬 설정
- 코딩 컨벤션 통일

2022-07-12 09:07 UTC, DomMorello requested changes
사소한 부분이긴 하지만 코멘트 달아놨습니다. 확인해주세요!

2022-07-12 13:43 UTC, compy-ryu commented on frontend/src/common/components/Button/index.tsx
> +  theme: PropTypes.oneOf(themeProps),
PropTypes에서 해당 목록을 재활용하기 위해 배열로 넣어뒀었습니다.
지금은 themeProps와 같이 정의하는 식으로 모두 변경해뒀어요!

2022-07-12 13:44 UTC, compy-ryu commented
하디형님 리뷰 반영 완료했숩니다!
시간 편하시고 몸 건강하실 떄 리뷰 부탁드립니다~~~~

2022-07-13 02:08 UTC, DomMorello approved these changes
리팩토링 좋았습니다!

2022-07-13 02:08 UTC, merged