PageSuspense 컴포넌트 구조 개선
woowacourse-teams/2022-review-duck pull request #635
Opened 2022-10-30 09:27 UTC by compy-ryu

## Recoil 없이, Context로 리렌더링 이슈 해결
Recoil과 Context가 한 컴포넌트에서 혼재되어있는 상황이 어색하여 Context로만 해결해보았습니다.

개선한 방법은
useContext를 사용하면, Provider value에 넣어둔 모든 값을 구독하기에
들어있는 값 중 한개라도 변경이 일어나도 해당 context를 사용하는 컴포넌트들 모두가 리렌더링이 일어납니다.

그리하여 Context에서 useState의 value와 setState 함수를 한개의 Context에 담는 것이 아닌
- value => IsPageLoadedContext
- setState => SetPageLoadedContext
와 같이 각각 담아 상태를 업데이트 하는 위치에서는 리렌더링이 되지 않도록 하여
리렌더링 이슈를 해결하였습니다.

사실 Recoil을 쓰는게 코드상 훨씬 깔끔하고 간결하지만...
학습 목적으로는 Context를 적용하는 것 좋을 것 같아, Context를 최종적으로 선택했습니다.

## PageSuspense 관련 네이밍 일괄 수정
MainLayout JSX에서

```jsx
<PageSuspense.Provider>
    {children}
</PageSuspense.Provider>
```
위와 같이 갑자기 Provider가 등장하는 것은 구조상 어색한 것 같아서

```jsx
// Main Layout
<PageSuspense>
    {children}
</PageSuspense>

// Page Component JSX
return PageSuspense.subscribe(
    <FlexContainer>캄피입니다.</FlexContainer>
)
```

위와 같이 네이밍 한번 정리했습니다.
그리고 Context를 2개 엮어서 사용 중이기에 PageSuspenseProvider로 묶어준 뒤
ContextWrapper에서 추가해주도록 변경했습니다.

2022-10-31 07:58 UTC, DomMorello requested changes
리팩토링 과정 아주 좋았습니다!

개인적으로 약간 피드백 드렸는데 확인해주시고 의견 주세요! ㅎㅎ

그런데 버그가 있는 것 같습니다. 오프라인에서 같이 해결해보시죠!

### 버그
최초 메인 페이지에서 다른 페이지로 이동할 때 Suspense의 fallback 컴포넌트가 무조건 TimeLinePage 로 렌더됩니다.
그리고 다른 페이지에서 MainPage로 이동할 때 의도한대로 Suspense가 작동하지 않고 흰 화면이었다가 메인페이지가 렌더됩니다.

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/App.tsx
> +          </UserAgentProvider>
context Provider를 이 곳에 선언하면 다른 레이아웃을 사용하는 곳에서도 한 번에 처리할 수 있어서 좋은 것 같습니다!

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/common/components/PageSuspense/Provider.tsx
> +type PageLoadedActionContextValue = React.Dispatch<SetStateAction<boolean>>;
SetPageLoadedType 이 조금 더 어울리는 것 같은데 네이밍에서 Action 을 포함한 이유가 있을까요?

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/common/components/PageSuspense/Provider.tsx
> +export const SuspenseFallbackContext = createContext<FallbackContextType | null>(null);
이렇게 context들이 파일 내부에 숨겨져있을 때 디렉토리 목록만 보고 context가 활용되는 컴포넌트인지 알기 어려울 수도 있을 것 같습니다.

같은 경로에 ProviderContext 라는 파일로 분리해서 관리하는 것은 어떨까요?

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/common/components/PageSuspense/index.tsx
> +  subscribe: PageChildrenWrapper,
해당 context를 사용하는 곳에서 subscribe 네이밍 좋은 것 같습니다!

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/common/components/PageSuspense/Provider.tsx
> +export const IsPageLoadedContext = createContext<boolean>(false);
두 컨텍스트로 나눠서 리렌더링 이슈를 해결했군요!

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/service/pages/UserProfilePage/index.tsx
> +  console.log('test');
제거해주세요!

2022-10-31 07:58 UTC, DomMorello commented on frontend/src/service/layout/MainLayout/index.tsx
>            <Suspense>
해당 Suspense 는 fallback도 없어서 제거해봤더니 잘 작동하던데 따로 있는 이유가 있을까요?
이미 PageSuspense 컴포넌트에서 Suspense 하위 컴포넌트를 감싸주고 있습니다.

2022-11-06 16:27 UTC, compy-ryu commented on frontend/src/common/components/PageSuspense/Provider.tsx
> +export const SuspenseFallbackContext = createContext<FallbackContextType | null>(null);
말씀주신 context들은 해당 컴포넌트 외부에서 사용되지 않기에 같은 파일 내에 위치시켰습니다.
아직까지는 코드 라인이 길지 않으니 유지하는게 좋을 것 같습니다.

오히려 어떤 Context에 어떤 값을 넣어주는지 바로 알 수 있어서 좋다 생각했어요!

2022-11-06 16:27 UTC, compy-ryu commented on frontend/src/common/components/PageSuspense/Provider.tsx
> +type PageLoadedActionContextValue = React.Dispatch<SetStateAction<boolean>>;
변경했습니다!

2022-11-06 16:28 UTC, compy-ryu commented on frontend/src/service/pages/UserProfilePage/index.tsx
> +  console.log('test');
헛 제거했습니다!

2022-11-06 16:29 UTC, compy-ryu commented on frontend/src/service/layout/MainLayout/index.tsx
>            <Suspense>
PageSuspense를 사용하지 않는 위치를 고려해서 한번 더 감싸주었습니다.
PageSuspense는 구독 중인 페이지 컴포넌트만 적용되기에, 현재 회고 도메인 레이아웃의 경우 PageSuspense를 사용하지 않아서 위와 같이 처리했습니다.

2022-11-06 16:29 UTC, compy-ryu commented
리뷰 진행 완료로 머지 진행합니다!

2022-11-06 16:29 UTC, merged